name: dynamic_slider
description: A custom implementation of Slider widget in Flutter that accepts values on a sliding scale.
version: 0.1.0-dev.1
repository: https://github.com/oaktreeapps/dynamic-slider

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

